name: Manually triggered workflow
on:
  push:
    branches:
    - triggertest
  pull_request:
    branches:
    - triggertest
  
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: print "hello from triggertest"
